-- tokens

DROP TABLE IF EXISTS tokens CASCADE;

CREATE TABLE tokens
(
	id                 BIGINT    NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

	uid                UUID      NOT NULL UNIQUE DEFAULT UUIDV7(),


	is_active          BOOLEAN   NOT NULL        DEFAULT TRUE,

	creation_timestamp TIMESTAMP NOT NULL        DEFAULT CLOCK_TIMESTAMP(),
	update_timestamp   TIMESTAMP NOT NULL        DEFAULT CLOCK_TIMESTAMP(),
	deletion_timestamp TIMESTAMP NULL,

	version            INTEGER   NOT NULL        DEFAULT 0
);

INSERT INTO tokens (is_active) VALUES (TRUE);